global:
  scrape_interval:  15s

scrape_configs:
  - job_name: 'product-service'
    metrics_path: '/q/metrics'
    static_configs:
      - targets:  ['host.docker.internal:8080']

  - job_name: 'order-service'
    metrics_path: '/q/metrics'
    static_configs:
      - targets: ['host.docker.internal:8081']

  - job_name:  'notification-service'
    metrics_path: '/q/metrics'
    static_configs:
      - targets: ['host.docker.internal:8082']